export const SET_ARTISTS = "SET_ARTISTS";
export const ERROR_MANAGER = "ERROR_MANAGER";
export const RESET_REDUCERS = "RESET_REDUCERS";
export const SET_GENRES = "SET_GENRES";
export const SET_ALBUMS_BY_ARTISTS = "SET_ALBUMS_BY_ARTISTS";
export const SET_SONGS_BY_ALBUM = "SET_SONGS_BY_ALBUM";
export const SET_RANDOM_SONG = "SET_RANDOM_SONG";
